WIP: Initial pass at BpfApplication CRD update for load/attach split
bpfman/bpfman-operator pull request #347
Opened 2024-12-09 23:53 UTC by anfredette

This still includes the attach info with the programs, but it is optional, and may be updated later.  This allows the program to be loaded before any attachments are made, and allows attachments to be added after the program has been loaded.

TODO: Add a per-node CRD (BpfProgram analog) to maintain the per-node state for the BpfApplication.

2024-12-10 22:32 UTC, anfredette commented
All of the examples will need to be updated with the new CRD format before they will pass.

2025-01-24 22:57 UTC, anfredette commented
I've cleaned up the code a bit and added support for TCX and Fentry.  See the TODO.md file for more details.

2025-02-20 11:50 UTC, dave-tucker requested changes
Some feedback on the API. The naming comments we can probably handle in a follow up as this API change isn't going to be backwards compatible anyway.
We should however fix the fentry/fexit and preferably drop `type: Xdp` before merge IMHO

2025-02-20 11:50 UTC, dave-tucker commented on PROJECT
> +  kind: BpfNsApplication
We agreed this would be `BpfApplication` and `ClusterBpfApplication`
But IIRC we wanted to get Billy's change in first before we changed the naming since this API change is the breaking one.

2025-02-20 11:50 UTC, dave-tucker commented on PROJECT
> +  kind: BpfNsApplicationState
So this would then be ClusterBpfApplicationState

2025-02-20 11:50 UTC, dave-tucker commented on config/samples/bpfman.io_v1alpha1_bpfapplication.yaml
> +    - bpffunctionname: kprobe_test
I really don't like `bpffunctioname`. It should either be `bpfFunctionName` or just `functionName` since we're in a `Bpf` CRD.. or hey, even just `function`

2025-02-20 11:50 UTC, dave-tucker commented on config/samples/bpfman.io_v1alpha1_bpfapplication.yaml
> +      type: Kprobe
Just wondering, is case significant here? It seems to me that `kprobe` or `KPROBE` or `Kprobe` should probably work. I'd prefer to use the lowercase version.

2025-02-20 11:50 UTC, dave-tucker commented on config/samples/bpfman.io_v1alpha1_bpfapplication.yaml
> +      type: Kprobe
Do we need to expose `type` here?
It can be inferred based on which of the optional fields are set so it seems redundant

2025-02-20 11:50 UTC, dave-tucker commented on config/samples/bpfman.io_v1alpha1_bpfapplication.yaml
> +        attach_points:
I think this should be `links` as we're expressing desired state.
The verb might be `attach`, but we're expecting `links` in the end.

2025-02-20 11:50 UTC, dave-tucker commented on config/samples/bpfman.io_v1alpha1_bpfapplication.yaml
> +        attach_points:
👀 inconsistent rules re: casing. k8s CRDs are supposed to be camelCase

2025-02-20 11:50 UTC, dave-tucker commented on config/samples/bpfman.io_v1alpha1_bpfapplication.yaml
> +          - func_name: try_to_wake_up
as above: `funcName`

2025-02-20 11:50 UTC, dave-tucker commented on config/samples/bpfman.io_v1alpha1_bpfapplication.yaml
> +          - interfaceselector:
`interfaceSelector`. I'm not going to comment on this anymore.
We seriously need to take a pass through the API to fix the inconsistencies.
We can do that in this PR, or later

2025-02-20 11:50 UTC, dave-tucker commented on config/samples/bpfman.io_v1alpha1_bpfapplication.yaml
> +        attach: true
```suggestion
    - function: fentry_test
      fentry:
        links:
          - function_name: do_unlinkat
```

This shouldn't deviate from the pattern in the other program types.
The fact we need the fn_name for `load()` and we can only attach it to one place are implementation details we shouldn't be exposing in the API.

2025-02-28 11:59 UTC, msherif1234 reviewed
not sure about renaming the agent files with `cl` is that for clusterscope ?

2025-02-28 11:59 UTC, msherif1234 commented on apis/v1alpha1/bpfApplication_types.go
>  	// ProgTypeUprobe refers to the Uprobe program type.
I don't know why u deleted the kproberet and uproberet program types ?

2025-02-28 11:59 UTC, msherif1234 commented on apis/v1alpha1/shared_types.go
> +	// or the eBPF program will not load.
we no longer have an object called `BpfProgram` so we should avoid using it everywhere in code and comments

2025-02-28 11:59 UTC, msherif1234 commented on controllers/bpfman-agent/cl-tc-program.go
> +		if containerInfo != nil && len(*containerInfo) != 0 {
nit no need to check the len range will handle that

2025-02-28 14:31 UTC, anfredette commented on apis/v1alpha1/bpfApplication_types.go
>  	// ProgTypeUprobe refers to the Uprobe program type.
They weren't being used.

2025-02-28 15:15 UTC, anfredette commented
> not sure about renaming the agent files with cl is that for clusterscope ?

Yes.  I was planning to rename things as follows:
cluster-scoped related files: cl_*
namespace-scoped related files: ns_*

2025-03-02 22:45 UTC, anfredette commented on PROJECT
> +  kind: BpfNsApplication
Done

2025-03-02 22:45 UTC, anfredette commented on PROJECT
> +  kind: BpfNsApplicationState
Done

2025-03-02 22:49 UTC, anfredette commented on config/samples/bpfman.io_v1alpha1_bpfapplication.yaml
> +    - bpffunctionname: kprobe_test
We made it "bpffunctionname" after much discussion a while back when we started using the bpf function name instead of a name defined in the section declaration.  We also wanted to disambiguate this function name from the name of the function that some bpf programs attach to.

That said, I don't like it either :-).  I changed "bpfunctionname" to just "name", and the "func_name" and "function_name" to just "function".

2025-03-02 23:02 UTC, anfredette commented on config/samples/bpfman.io_v1alpha1_bpfapplication.yaml
> +      type: Kprobe
Yes and no.  Left unchecked, I don't think Kubernetes would care, but it is case sensitive in that kubernetes passes these values through to the controller code in the case that the user enters them.  However, we also have validation logic that only allows one case, so in our case (no pun intended) it is case sensitive.  If we wanted to support case insensitivity, we'd have to handle it in our code.

I made everything lower case.  We can disuss whether to use camelCase instead.

2025-03-02 23:23 UTC, anfredette commented on config/samples/bpfman.io_v1alpha1_bpfapplication.yaml
> +      type: Kprobe
This is implemented this as union, and Type is the "unionDiscriminator".  This tells us which of the "unionMembers" will be populated, and validation logic ensures that if the Type is X, the program info for X is populated.  @msherif1234 used this pattern for the original BpfApplication CRD. There may be another way to implement the API, but this works.

2025-03-02 23:23 UTC, anfredette commented on config/samples/bpfman.io_v1alpha1_bpfapplication.yaml
> +        attach_points:
Done

2025-03-02 23:25 UTC, anfredette commented on config/samples/bpfman.io_v1alpha1_bpfapplication.yaml
> +        attach_points:
Is the JSON representation supposed to be camelCase?

2025-03-02 23:25 UTC, anfredette commented on config/samples/bpfman.io_v1alpha1_bpfapplication.yaml
> +          - func_name: try_to_wake_up
It's now just function

2025-03-02 23:26 UTC, anfredette commented on config/samples/bpfman.io_v1alpha1_bpfapplication.yaml
> +        attach: true
I've changed the pattern.

2025-03-02 23:27 UTC, anfredette commented on apis/v1alpha1/shared_types.go
> +	// or the eBPF program will not load.
I got rid of a lot of it, but there's still more work to do.

2025-03-02 23:27 UTC, anfredette commented on controllers/bpfman-agent/cl-tc-program.go
> +		if containerInfo != nil && len(*containerInfo) != 0 {
Done.

2025-03-03 14:53 UTC, anfredette commented on config/samples/bpfman.io_v1alpha1_bpfapplication.yaml
> +      type: Kprobe
I just went back and changed all of the json tags to camelCase

2025-03-05 18:20 UTC, Billy99 approved these changes
Work needs to be done on the integration tests. Merging with integration tests failing and work off main to get tests passing again.

2025-03-05 18:25 UTC, merged