Add pprof port to bpfagent controller
bpfman/bpfman-operator pull request #40
Opened 2024-07-09 20:47 UTC by msherif1234

2024-07-10 15:19 UTC, dave-tucker requested changes

2024-07-10 15:19 UTC, dave-tucker commented on cmd/bpfman-agent/main.go
> +	_ "net/http/pprof"
I think you can remove this import.
IIRC this adds the routes to the default ServeMux... 
However, you're passing the bind port through to controller-runtime, which doesn't use the default ServeMux...

2024-07-15 15:18 UTC, anfredette approved these changes
LGTM

2024-07-15 16:52 UTC, dave-tucker approved these changes

2024-07-15 16:52 UTC, merged